      SUBROUTINE ASPECT(AJUNK)
C
C  DUMMY ROUTINE FOR ZETA EXTENSION TO CALCOMP LIBRARY.
C  IF YOU HAVE ZETA, LOAD WITH ZETA LIBRARY, OTHERWISE THIS
C  ROUTINE SERVES AS NULL ROUTINE.
C
      RETURN
      END
      SUBROUTINE DASHDF(I1,I2,I3,I4)
C
C  DUMMY ROUTINE FOR ZETA EXTENSION TO CALCOMP LIBRARY.
C  REPLACE WITH ZETA LIBRARY IF HAVE ZETA PLOTTER.
C
      RETURN
      END
       SUBROUTINE DASHS(ARRAY,IJUNK)
C
C  DUMMY ROUTINE FOR CALCOMP LIBRARY ROUTINE DASHS.
C  REPLACE WITH CLACOMP LIBRARY ROUTINE IF AVAILABLE.
C
       DIMENSION ARRAY(*)
       RETURN
       END
      SUBROUTINE NEWPEN(IPENNO)
C
C     PROVIDE DUMMY ROUTINES FOR THE CALCOMP LIBRARY
C     ROUTINES FOR SITES THAT DO NOT HAVE IT.
C
      PRINT *, 'CALCOMP LIBRARY ROUTINE "NEWPEN" NOT SUPPORTED'
      RETURN
      END
      SUBROUTINE PLOT(X,Y,IPEN)
C
C     PROVIDE DUMMY ROUTINES FOR THE CALCOMP LIBRARY
C     ROUTINES FOR SITES THAT DO NOT HAVE IT.
C
      PRINT *,'CALCOMP LIBRARY ROUTINE "PLOT" NOT SUPPORTED'
      RETURN
      END
      SUBROUTINE PLOTS(I1,I2,I3)
C
C     PROVIDE DUMMY ROUTINES FOR THE CALCOMP LIBRARY
C     ROUTINES FOR SITES THAT DO NOT HAVE IT.
C
      PRINT *,'CALCOMP LIBRARY ROUTINE "PLOTS" NOT SUPPORTED'
      RETURN
      END
      SUBROUTINE NUMBER(X,Y,H,ANUM,THETA,IDUM)
C
C     PROVIDE DUMMY ROUTINES FOR THE CALCOMP LIBRARY
C     ROUTINES FOR SITES THAT DO NOT HAVE IT.
C
      PRINT *,'CALCOMP LIBRARY ROUTINE "NUMBER" NOT SUPPORTED'
      RETURN
      END
      SUBROUTINE SYMBOL(XPOS,YPOS,HEIGHT,ITEXT,ANGLE,NUMCHR)
C
C     PROVIDE DUMMY ROUTINES FOR THE CALCOMP LIBRARY
C     ROUTINES FOR SITES THAT DO NOT HAVE IT.
C
      CHARACTER*(*) ITEXT
C
      PRINT *,'CALCOMP LIBRARY ROUTINE "SYMBOL" NOT SUPPORTED'
      RETURN
      END
      SUBROUTINE LINE (X,Y,NN,K,J,L) 
C
      REAL X(*), Y(*)
C
      PRINT *,'CALCOMP LIBRARY ROUTINE "LINE" NOT SUPPORTED'
C
      RETURN
      END  
