      SUBROUTINE XCHECK(IERROR)
      RETURN
      END
      SUBROUTINE XRDLOC(IX,IY,IERROR)
      RETURN
      END
      SUBROUTINE XINIT(IXP,IYP,IORIEN,IXRET,IYRET,IERROR)
      WRITE(*,*) ' X11 HAS NOT BEEN INSTALLED AT YOUR SITE'
      WRITE(*,*) ' CONTACT YOUR LOCAL SITE COORDINATER FOR '
      WRITE(*,*) ' MORE INFORMATION'
      RETURN
      END
      SUBROUTINE XERASE(IX,IY,IORIEN,IXRET,IYRET,IBACK,IFLAG)
      RETURN
      END
      SUBROUTINE XUPDAT
      RETURN
      END
      SUBROUTINE XCLEAR
      RETURN
      END
      SUBROUTINE XEND
      RETURN
      END
      SUBROUTINE XFORE(INDEX)
      RETURN
      END
      SUBROUTINE XLATTR(INDEX,ICODE)
      RETURN
      END
      SUBROUTINE XDRAW(IX,IY,NPTS)
      INTEGER IX(*), IY(*)
      RETURN
      END
      SUBROUTINE XPOINT(IX,IY)
      RETURN
      END
      SUBROUTINE XREGFL(IX,IY,NPTS)
      INTEGER IX(*), IY(*)
      RETURN
      END
      SUBROUTINE XTATTR(IFONT,IERROR)
      INTEGER IFONT(*)
      RETURN
      END
      SUBROUTINE XTEXTH(ISTRNG,IXPOS,IYPOS,IJUSTH,IJUSTV,IERROR)
      INTEGER ISTRNG(*)
      RETURN
      END
      SUBROUTINE XTEXTV(ISTRNG,IXPOS,IYPOS,IJUSTH,IJUSTV,IERROR)
      INTEGER ISTRNG(*)
      RETURN
      END
